version: "3.9"

services:

    nginx:
        image: wodby/nginx
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        depends_on:
            - php
        environment:
            NGINX_STATIC_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
            NGINX_SERVER_ROOT: /var/www/html/www
        volumes:
            - ./src/:/var/www/html
        networks:
            - web
        labels:
            # Route Traefik
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.middlewares=aiti_auth@file"
            - "traefik.http.routers.${PROJECT_NAME}_http.entrypoints=web"
            - "traefik.http.routers.${PROJECT_NAME}_http.rule=Host(`${PROJECT_BASE_URL}`)"

            # HTTPS redirect + resolver
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_http.middlewares=${PROJECT_NAME}_https_redirect"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.permanent=true"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls.certresolver=myresolver"

    php:
        image: wodby/php:8
        container_name: "${PROJECT_NAME}_php"
        restart: always
        environment:
            PHP_FPM_CLEAR_ENV: 'no'
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./src:/var/www/html
        depends_on:
            - composer
            - database
        networks:
            - database
            - web

    composer:
        container_name: "${PROJECT_NAME}_composer"
        image: composer
        command: install
        volumes:
            - ./src:/app

    adminer:
        image: adminer
        container_name: "${PROJECT_NAME}_adminer"
        environment:
            ADMINER_DEFAULT_SERVER: database
        networks:
            - database
            - web
        restart: always
        depends_on:
            - database
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_adminer.middlewares=aiti_auth@file"
            - "traefik.http.routers.${PROJECT_NAME}_adminer.entrypoints=web"
            - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"

    database:
        image: wodby/mariadb
        container_name: "${PROJECT_NAME}_mariadb"
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
            - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - database

networks:
    database:
        name: database_release
    web:
        name: release_jandolejs_cz
