version: "3"

services:

    nginx:
        image: wodby/nginx:$NGINX_TAG
        container_name: "${PROJECT_NAME}_nginx"
        depends_on:
            - php
        environment:
            NGINX_STATIC_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
            NGINX_SERVER_ROOT: /var/www/html/www
        volumes:
            - ./src/:/var/www/html:cached
        labels:
            # Enable traefik for this container
            - "traefik.enable=true"

            # Route HTTP Web
            - "traefik.http.routers.${PROJECT_NAME}_http.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_http.entrypoints=web"

            # Route HTTPS Web
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"

            # Redirect HTTP to HTTPS
            - "traefik.http.routers.${PROJECT_NAME}_http.middlewares=${PROJECT_NAME}_https_redirect"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.permanent=true"

            # TLS Certificates
            - "traefik.http.routers.${PROJECT_NAME}_https.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls.certresolver=myresolver"


    php:
        image: wodby/php:$PHP_TAG
        container_name: "${PROJECT_NAME}_php"
        environment:
            PHP_FPM_CLEAR_ENV: 'no'
            PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
            DB_HOST: $DB_HOST
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            DB_NAME: $DB_NAME
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./src:/var/www/html:cached
        depends_on:
            - mariadb
            - composer

    mariadb:
        image: wodby/mariadb:$MARIADB_TAG
        container_name: "${PROJECT_NAME}_mariadb"
        stop_grace_period: 30s
        environment:
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
        volumes:
            #- ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
            - ./mysql:/var/lib/mysql # I want to manage volumes manually.

    composer:
        container_name: "${PROJECT_NAME}_composer"
        image: composer
        command: install
        volumes:
            - ./src:/app

    adminer:
        image: adminer
        container_name: "${PROJECT_NAME}_adminer"
        environment:
            ADMINER_DEFAULT_SERVER: $DB_HOST
        labels:
            # Enable traefik for this container
            - "traefik.enable=true"

            # Route HTTP Web
            - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_adminer.entrypoints=web"
