version: "3.9"

services:

    nginx:
        image: wodby/nginx
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        depends_on:
            - php
        environment:
            NGINX_STATIC_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
            NGINX_SERVER_ROOT: /var/www/html/www
        volumes:
            - ./src/:/var/www/html
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_http.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}_http.rule=Host(`www.${PROJECT_BASE_URL}`) || Host(`${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_http.entrypoints=web,websecure"

    php:
        image: wodby/php:8
        container_name: "${PROJECT_NAME}_php"
        restart: always
        environment:
            PHP_FPM_CLEAR_ENV: 'no'
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./src:/var/www/html
        depends_on:
            - composer
        networks:
            - web

    composer:
        container_name: "${PROJECT_NAME}_composer"
        image: composer
        command: install
        volumes:
            - ./src:/app


networks:
    web:
        name: www_release
        external: true
